In [1]:
import numpy as np

In [2]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.random.seed(101)

In [4]:

arr = np.random.randit(0, 100, 10)

AttributeError: module 'numpy.random' has no attribute 'randit'

In [5]:
arr = np.random.randint(0, 100, 10)

In [6]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [7]:
arr2 = np.random.randint(0, 100, 10)

In [8]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [9]:
arr.reshape(2, 5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [13]:
mat = np.arange(0,4).reshape(2,2)

In [14]:
mat

array([[0, 1],
       [2, 3]])

mat[1,0]

In [15]:
mat[1,0]

2

In [16]:
mat[0,1]

1

In [18]:
mat[:, 0]

array([0, 2])

In [19]:
mat[:, 1]

array([1, 3])

In [20]:
mat[1, :]

array([2, 3])

In [21]:
mat = np.arange(0,100).reshape(10,10)

In [22]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
mat[0:3, 0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [24]:
mat[0:3, 0:4] = 0

In [25]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])